openSUSE/rpm-config-SUSE

suse_macros.in
If only a shared library and its language package exist, then there are
two ways:
`%lang_package -n libconfuse2`: Creates an unwanted
"libconfuse2-lang", but at least it depends on "libconfuse2".
`%lang_package -r libconfuse2`: Creates a "libconfuse-lang", but adds
an unwanted dependency on "libconfuse".
Rewrite the %lang_package macro such that the presence of any -r
argument inhibits implicit Requires.
---
There is just one package in openSUSE that even uses `-r`, so there is no extra work really.
=> %lang_package: avoid requirement on shared library providing extra symbols

macros.d/macros.initrd
Many packages need BuildRequires on suse-module-tools only for
the sake of having the "regenerate-initrd" macros defined.
These macros can't be associated with a certain package group
like the python macros. They should be in rpm-config-SUSE.
=> Added macros.d/macros.initrd

package/rpm-config-SUSE.changes, suse_macros.in
If /bin/sh is not bash (like if you use busybox), %install_info fails with a syntax error.
=> Don't use bash syntax with /bin/sh

macros.d/macros.initrd
From @jengelh:
${//} type substitution is not understood by shells like dash.
See https://github.com/openSUSE/suse-module-tools/pull/6
=> macros: avoid emitting bashisms into scriptlets

fileattrs/kernel.attr, fileattrs/kmp.attr, scripts/find-provides.ksyms, scripts/find-requires.ksyms, scripts/find-supplements.ksyms
This patch modifies a few scripts and attr files to support the
compressed module files.  Both gz and xz compressions are supported.
A tricky fix is the change in find-requires.ksyms.  Since the script
calls nm, we need to expand it to temporary files, just like
find-provides.ksyms already does.
Bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1135854
Signed-off-by: Takashi Iwai <tiwai@suse.de>
=> Add support for compressed kernel modules

scripts/firmware.prov
The upcoming kernel will support the compressed firmware files, and
this patch corresponds to that kernel change, fixing firmware.prov to
deal with the xz-compressed firmware files as well.
Signed-off-by: Takashi Iwai <tiwai@suse.de>
=> Add support for compressed firmware files

scripts/find-requires.ksyms
modinfo and modprobe are required to generate kABI dependencies but
generic dependecies are fine without.
Signed-off-by: Michal Suchanek <msuchanek@suse.de>
=> find-requires.ksyms: Move modinfo and modprobe before the ksym dependency code.

suse_macros.in
As discussed on opensuse-packaging, new variable to make migration to /usr/etc proposal easier.
=> Add _distconfdir as /usr/etc

fileattrs/locale.attr, scripts/locale.prov, suse_macros.in
For packages that ship mo files, add automatic provides for the
corresponding locale instead of an unconditional Supplements.
That way the lang subpackage won't be installed on English only
installations.
The mechanism requires to stick to the common openSUSE naming
convention that a package "foo" has it's translations in a package
called "foo-lang".
Requires https://github.com/rpm-software-management/rpm/pull/575
=> Add macros for locale provides

scripts/locale.prov
There are some packages that use -locale instead of -lang for legacy
reasons, such as glibc and gcc.
=> locale.prov: also work with -locale packages

macros.d/macros.ldconfig, package/rpm-config-SUSE.changes
It's just too annoying not having these, and it's basically no effort/burden to have them.
=> Add ldconfig_scriptlets macros for RH/Fedora compatibility

suse_macros.in
Many packages use, based on the packaging guidelines, something like this:
%preun
if [ "$1" -eq "0" ] ; then
%install_info --delete --info-dir=%{_infodir}…
fi
With %install_info translated to %nil, this results in syntax errors by
script interpreters, as the if/fi block is empty. Work around this by
translating into a command without action.
=> Make deprecated %install_info not fail when used within if/fi construct

suse_macros.in
grep was never required by fillup, diffutils is not needed anymore since 2008.
Replace coreutils with files to allow usage of busybox.
=> Remove grep and diffutils from fillup_prereq, replace coreutils with file requires

fileattrs/locale.attr
As per discussion on the packaging list there are several packages that
install their mo files into a custom location rather than
/usr/share/locale. So relax the regexp to also catch those.
=> Don't limit locale match to /usr/share/locale

macros.d/macros.obs
Nothing in openSUSE:Factory uses these.
=> macros.obs: remove unused macros

fileattrs/firmware.attr, suse_macros.in
So far all packages hardcode the path themselves. A global define will
help moving all packages shipping firmware in case that turns out to
be needed (boo#1029961)
=> Define a global %_firmwaredir

fileattrs/modulesload.attr
We've got modules-load.d style dependenices since 52cc7dc, but they
aren't actually generated because we're lacking a fileattr for
modules-load.d files.
Add it.
(Note: I still need to test this).
=> find-requires.ksyms: actually generate modules-load.d dependencies

scripts/find-requires.ksyms
Without this, kmod-dependencies may blow up e.g. container images. This has happened in the past, and has caused the kmod requires to have to be taken back for both factory and SLE.
SLE architects are tackling this issue now with the conditional dependency.
This is obviously related to #36, which should rather not be pushed to Factory without this fix.
=> find-requires.ksyms: use "if kernel" conditional for modules-load.d

scripts/find-provides.ksyms
Because IFS is set to \n the unzip variable is not split at space
resulting in
/usr/lib/rpm/find-provides.ksyms: line 65: xz -cd: command not found
Move the -cd argument to the unzip invocation so that there is no need
to split the variable.
Fixes: #45
Fixes: 6cd29a8 ("Add support for compressed kernel modules")
Signed-off-by: Michal Suchanek <msuchanek@suse.de>
=> find-provides.ksyms: Fix compressed modules.

fileattrs/locale.attr
Some packages that use custom locale directories use
"locales" instead of "locale" so .mo files have to
be found there too.
This is part of the fix for
https://bugzilla.opensuse.org/show_bug.cgi?id=1190251
=> Allow locale directory to be named "locales" too

scripts/find-provides.ksyms
Changing IFS makes the following code behave unexpectedly and it already
caused #45. Use the default IFS.
Signed-off-by: Michal Suchanek <msuchanek@suse.de>
=> find-provides.ksyms: Do not set IFS - it is not needed for anything.

fileattrs/locale.attr
There are more than just gettext catalogs, like Qt translation files (.qm).
=> locale.attr: Match all files inside LC_MESSAGES (boo#1194865)

package/rpm-config-SUSE.changes, package/rpm-config-SUSE.spec, suse_macros.in
echo -e only exists in bash, we can use printf which is also
available in POSIX shells like /bin/sh
=> Avoid bash specific construct

package/rpm-config-SUSE.spec
The previously used "SUSE Linux" is ambiguous, we can make it more
explicit by saying "SUSE" and "openSUSE" as product families.
=> Explain that rpm-config-SUSE covers also openSUSE

suse_macros.in
Fixes https://bugzilla.opensuse.org/show_bug.cgi?id=1137381
=> Fix bug not using custom name for summary and description in language packages (boo#1137381)

macros.d/macros.debuginfo
We don't support parallel installation of the same debuginfo - and so
don't patch the binaries to create unique build ids. Unfortunately
we can't just define the macros affecting the behaviour of
debug_install_post as the version in rpm triggers on defined macros
and we can't undefine it
=> Redefine %__debug_install_post to simplify debuginfo setup

macros.d/macros.sbat, package/rpm-config-SUSE.spec
Define all macros in macros.sbat with suffixes and then check at runtime whether %is_opensuse is true
https://build.opensuse.org/package/rdiff/openSUSE:Factory/shim?linkrev=base&rev=102
=> Fix SLE sbat macros used on Leap (bsc#1198458)

macros.d/macros.initrd
mkdir is part of the coreutils package. When the post scriptlet of some
package using regenerate_initrd_post is run, the mkdir command may be
unavailable. This is non-fatal, because in all cases that matter for initrd
generation, coreutils will be part of the same transaction and will trigger
an initrd rebuild later. See boo#1217775.
Anyway, packages can use the regenerate_initrd_requires macro below to make
sure mkdir is available in their post scriptlet. Use if this macro is not
mandatory.
Signed-off-by: Martin Wilck <mwilck@suse.com>
See also https://github.com/openSUSE/suse-module-tools/pull/99
=> macros.initrd: %regenerate_initrd_post: don't fail if mkdir is unavailable

fileattrs/kernel.attr, fileattrs/kmp.attr, fileattrs/modulesload.attr, scripts/find-provides.ksyms, scripts/find-requires.ksyms
With this we will get our ksym provides scripting tested in Factory, avoid invalid version warning for kernel-uname-r, and avoid wrong requires when modules are not installed in the module directory of the kernel they are built for.
=> scripts: Do full ksyms dependencies on Tumbleweed

scripts/find-provides.ksyms
The find-provides.ksyms uncompresses the kernel module into a temporary file to pass it to the ksym-provides tool that does not support compression.
modinfo tool form current kmod version refuses to provide information for files not ending in .ko.
Add .ko suffix to the temporary file.
Alternatives:
- use modinfo on the compressed file
- revert the modinfo change that enforces module filenames ending in .ko
=> find-provides.ksyms: Fix ksym provides on Tumbleweed/ALP

suse_macros.in
* %set_permission should not bail out if chkstat fails, it should handle the failure more grateful. See bsc#1219736.
* Calling `zypper --install-root` could cause a failure with chkstat due to an unavailability of /proc. Instead of abort an installation / update of an RPM that will result in an undefined state for the system, ignore the error message. The user can fix this by calling chkstat themself.
=> set_permissions: handle chkstat failure more grateful

suse_macros.in
Packages which use %lang_package and are based on a library will conflict with each other in filelist but have differing names which will trigger an installcheck error
Provide an option to provide RPM deps with the helper
The intention is for the 'basename' to be the name of installed lang files to provide continuity, although for fast fixes of this issue the old package name can be used
=> lang_package: Add 'basename' option

package/rpm-config-SUSE.spec, suse/macros, suse_dist_macros.in
This simplifies the structure and prepares for future cleanups of the macros.
=> Split the SUSE distribution version macros to a separate file

suse/macros
In the expansion of the %requires_eq macro the output is stored in a variable and then it's printed with "echo". This patch adds quotes to the variable so breaklines are not removed from the final output.
See https://bugzilla.opensuse.org/show_bug.cgi?id=1233513
=> %requires_eq|ge(): Fix multiline output

suse/macros
Define `%jobs` as variable ([boo#1237231](https://bugzilla.suse.com/show_bug.cgi?id=1237231)) for reproducible builds.
Without this patch, obs-build would set %jobs to a constant that depends on the number of cores assigned to a build worker VM, making it hard to verify build results.
=> Define %jobs as variable (boo#1237231)

fileattrs/kmp.attr
The match in kmp.attr tries to match only KMP modules and exclude kernel modules. This does not work well because the regular expression is too restrictive. The scripts detect and exclude kernel modules anyway, just run them for all modules indiscriminately.
=> kmp.attr: Run scripts for all modules (bsc#1237308).

package/rpm-config-SUSE.spec
PR https://github.com/openSUSE/rpm-config-SUSE/pull/81 added leap_version to the listed distros - but the relevant code in the .spec file to set this to 0 in case leap_version is not defined in prjconf, was missing, resulting in the now published/installed file to contain
```
%leap_version @leap_version@
```
This in turn results in errors in packages like 'knot':
`[   13s] error: /home/abuild/rpmbuild/SOURCES/knot.spec:67: bad %if condition:  01699 > 1320 || 0@leap_version@ == 420300`
=> packaging: replace @leap_version@ in suse_dist_macros.in

macros.d/macros.reproducible-builds, package/rpm-config-SUSE.spec, suse/macros
Some moved from prjconf,
some added for rpm-4.20's new way of doing things
and some dropped that should no more be needed with 4.20
=> Add macros for reproducible-builds
